language: node_js
matrix:
  include:
  - node_js:
    - '6'
    env:
    - CAN_DEPLOY=true
before_install:
- npm -g install npm@4
script: npm run ci
notifications:
  email: false
deploy:
  provider: npm
  email: accounts@resin.io
  api_key:
    secure: V4B3b8h77wFH5R/fy3kr6U08HIHY7xHNUJaCX/3ZBtwSIiPmu1vmL1I2cF5awl2WnoYunCLKnPTitQj2UzkE2NP4zsdcAben2A95ZG3ZX70LKNh7tcfxJVz39nAuIbNt1UsQkLHPMbGwxqAXVu78en/pbNcKNCkwt2WzQzdJr2B+B1ae9yJeDL6EQDJfc3l2icSk9CsVriOT5yBkouwW2W28dAoN4FtR1ODpWerGcBbV2X4PO+uSGFAk53Y6v9t5/+QnqqWzRy9OmDUjDW5AcwvOBlVW9raiqTFILteqpbRiLR2Uu8Y3juc2xU6ZTz05L1nY2jjdcxX2muAFeZmqkPm4waYqpBS5L5R6GJcnkm62Po7TGcK7GHVoUycsVlA1wklkF1eK7HzGbrq//19JLE3/ghoqEUMYkbnl5udmIjbEw3oUYjwrQkJYQgMZsKYtRvpi7m2NfJMv2g+X+pnFXG88+9G65f+bqVkoWX28/h0YI/3nZBtQZXf41ivdefHbEUaLyutqdm0whfxWNXT3fI0xLGuaVh+v/XqJXw5LpMRw3B0XFeC9Bdg7kZHguu9Ql6FUpOLEvm+92FOhL7+n348jSDNqv3FeSugpGoSXyPc6dWiKHFF6CGHdRx52Ukw22ftl4bnBCY/uaBM2FyFhvg3H31iwqMc+44iDoD8aVco=
  on:
    # Deploys happen if there's a tag, it's a version number, and this row in the matrix has '$CAN_DEPLOY'
    tags: true
    condition: $CAN_DEPLOY = 'true' && $TRAVIS_TAG =~ ^v?[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
    repo: resin-io-modules/resin-auth
